MVCProjectCompany/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCProjectCompany.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Login")]
        public string Username { get; set; }

        [Required]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememeberMe { get; set; }
    }
}

MVCProjectCompany/Models/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCProjectCompany.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCProjectCompany.Models.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;
        public SidebarViewComponent(DataManager data)
        {
            this.dataManager = data;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            return Task.FromResult((IViewComponentResult) View("Default", dataManager.ServiceItems.GetServiceItems()));
        }
    }
}

MVCProjectCompany/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCProjectCompany.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCProjectCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        public HomeController(DataManager data)
        {
            this.dataManager = data;
        }
        public IActionResult Index()
        {
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

MVCProjectCompany/Areas/Admin/Controllers/ServiceItemsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCProjectCompany.Domain;
using MVCProjectCompany.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MVCProjectCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ServiceItemsController(DataManager data, IWebHostEnvironment env)
        {
            this.dataManager = data;
            this.hostingEnvironment = env;
        }

        
        public IActionResult Edit(Guid id)
        {
            ServiceItem service = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
            return View(service);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ServiceItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    string path = "/images/" + titleImageFile.FileName;
                    using (var fileStream = new FileStream(hostingEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await titleImageFile.CopyToAsync(fileStream);
                    }
                }
                dataManager.ServiceItems.SaveServiceItem(model);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.ServiceItems.DeleteServiceItem(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

MVCProjectCompany/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using MVCProjectCompany.Domain;
using MVCProjectCompany.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCProjectCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            TextField field = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(field);
        }

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }
    }
}

MVCProjectCompany/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVCProjectCompany.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCProjectCompany.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        public AccountController(UserManager<IdentityUser> user, SignInManager<IdentityUser> signIn)
        {
            this.userManager = user;
            this.signInManager = signIn;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }    

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.Username);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememeberMe, false);
                    if (result.Succeeded)
                        return Redirect(returnUrl ?? "/");
                }
                ModelState.AddModelError(nameof(LoginViewModel.Username), "Incorrect username or password");
            }
            return View(model); 
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

MVCProjectCompany/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCProjectCompany.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCProjectCompany/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using MVCProjectCompany.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCProjectCompany.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager dataManager;
        public ServicesController(DataManager data)
        {
            this.dataManager = data;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("ParticularService", dataManager.ServiceItems.GetServiceItemById(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageServices");
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

MVCProjectCompany/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ServiceItem>
@{
    ViewBag.Title = "Admin dashboard";
}

<div>
    <h1>@ViewBag.Title</h1>
    <div>
        <h3>Our services</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Add a new service</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (ServiceItem service in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@service.Id">Edit</a>

                        <form style="display: inline-block;" id="form-@service.Id" method="POST"
                              asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete">

                            <input type="hidden" name="id" value="@service.Id" />
                            <a href="#" onclick="document.getElementById('form-@service.Id').submit();">Delete</a>

                        </form>

                        <a asp-area="Admin" asp-controller="Services" asp-action="Index" asp-route-id="@service.Id">@service.Title</a>
                    </div>
                }
            </div>
        }

        <div class="div-box">
            <h3>Edit text fields of the website</h3>
            <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Main page</a>
            <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Our services</a>
            <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Our contacts</a>
        </div>

        <div class="div-box">
            <form asp-area="" asp-controller="Account" asp-action="Logout" method="POST">
                <input type="submit" value="Logout" />
            </form>
        </div>
    </div>
</div>

MVCProjectCompany/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem
@{
    ViewBag.Title = "Edit a service";
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@ViewBag.Title</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="POST" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>

            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>

            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>

            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>

            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>

            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>

            <input type="submit" value="Save" />
        </form>
    </div>
</div>

<script>
    window.onload = function () {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x => x.Text)');
        newCKEdit.updateElement();
    }
</script>

MVCProjectCompany/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    ViewBag.Title = "Edit a post";
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@ViewBag.Title</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="POST" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>

            <input type="submit" value="Save" />
        </form>
    </div>
</div>

<script>
    window.onload = function () {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x => x.Text)');
        newCKEdit.updateElement();
    }
</script>

MVCProjectCompany/Views/Home/Contacts.cshtml
@model TextField;
@{
    Layout = "_Layout";
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    @Html.Raw(Model.Text)
</div>

MVCProjectCompany/Views/Home/Index.cshtml
@{ 
    Layout = "_Layout";
}

<div>
    <h2>Hey it's me! The View from HomeController</h2>
</div>

MVCProjectCompany/Views/Services/Index.cshtml
@model IQueryable<ServiceItem>
@{
    TextField Contacts = ViewBag.TextField;
    ViewBag.Title = Contacts.Title;
    ViewBag.Description = Contacts.MetaDescription;
    ViewBag.Keywords = Contacts.MetaKeywords;
}

@if (Model.Any())
{
    @foreach (ServiceItem service in Model)
    {
        @await Html.PartialAsync("ServiceItemPartial", service);
    }
}

MVCProjectCompany/Views/Services/ParticularService.cshtml
@model ServiceItem
@{ 
    ViewBag.Title = Model.Title;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords; 
}

<div>
    <h2>@Model.Title</h2>
    <h2>@Model.Subtitle</h2>
    <div>
        <img class="img-block" src="~/images/@Model.TitleImagePath"/>
    </div>
</div>

<div>
    @Html.Raw(Model.Text)
</div>

MVCProjectCompany/Views/Shared/Components/Sidebar/Default.cshtml
@model IQueryable<ServiceItem>

@if (Model.Any())
{
    <section>
        <h2>Our services</h2>
        <ul class="small-image-list">
            @foreach(ServiceItem service in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@service.Id">
                        <img src="~/images/@service.TitleImagePath" class="left"/>
                    </a>
                    <h4>@service.Title</h4>
                    <h4>@service.Subtitle</h4>
                </li>
            }
        </ul>
    </section>
}

MVCProjectCompany/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.min.css" asp-append-version="true" />

MVCProjectCompany/Views/Shared/FooterPartial.cshtml
<div id="footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div id="copyright">
                    &copy; @Config.CompanyName. All rights reserved.
                </div>

            </div>
        </div>
    </div>
</div>

MVCProjectCompany/Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <header id="header">
                    <h1><a href="/" id="logo">@Config.CompanyName</a></h1>
                    <nav id="nav">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Services</a>
                        <a asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
                    </nav>
                </header>

            </div>
        </div>
    </div>
</div>

MVCProjectCompany/Views/Shared/MetatagsPartial.cshtml
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}
@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}
@* Dynamically set the description tag, title tag and keywords to search for ViewBag Title, Description and Keywords. *@
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

MVCProjectCompany/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

MVCProjectCompany/Views/Shared/ServiceItemPartial.cshtml
@model ServiceItem

<div class="div-box">
    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@Model.Id">
        <img src="~/images/@Model.TitleImagePath" alt="" class="img-block"/>
    </a> 
    <h2>@Model.Title</h2>
    <p><h3>@Model.Subtitle</h3></p>
</div>

MVCProjectCompany/Views/Shared/SidebarPartial.cshtml
<div class="col-4 col-12-medium">
    <cache>
        @(await Component.InvokeAsync<SidebarViewComponent>())
    </cache>
</div>

MVCProjectCompany/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    <div id="page-wrapper">

        @await Html.PartialAsync("HeaderPartial")

        <div id="main">
            <div class="container">
                <div class="row main-row">
                    <div class="col-8 col-12-medium">
                        @RenderBody()
                    </div>
                    @await Html.PartialAsync("SidebarPartial")
                </div>
            </div>
        </div>

        @await Html.PartialAsync("FooterPartial")

    </div>



    @await Html.PartialAsync("ScriptsPartial")
</body>
</html>